;
; File generated by cc65 v 2.16 - Git N/A
;
	.fopt		compiler,"cc65 v 2.16 - Git N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__

	.export		_random, _randomise

.segment	"BSS"
_seed:
	.res	4,$00
	
.segment	"RODATA"
	
; ---------------------------------------------------------------
; void __near__ randomise (long __seed)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_randomise: near

.segment	"CODE"
;
	jsr     pusheax
	
	sta     _seed
	stx     _seed+1
	ldy     sreg
	sty     _seed+2
	ldy     sreg+1
	sty     _seed+3

	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; long __near__ random (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_random: near

.segment	"CODE"


;
;	Push Random Seed onto C stack	
;
	lda		_seed+3
	sta		sreg+1
	lda		_seed+2
	sta		sreg+0
	ldx		_seed+1
	lda		_seed+0
	jsr     steax0sp
;
; 	Flip Bit 2
;
	jsr     ldeax0sp
	eor     #$01
	jsr     steax0sp	
;
; 	Multiply Random Seed by 2, 
;	then roll Bit 32 back to Bit 0
;
	jsr     ldeax0sp
	clc
	jsr     asleax1
	adc		#$00			; Add Zero plus the Carry Bit
	jsr     steax0sp
;
; 	Random Seed + 1;
;
	; lda     #$00
	; sta     sreg+1
	; sta     sreg
	; lda     #$01
	; ldx     #$00
	; jsr     laddeq0sp

;
;	Pop Random Seed off C stack and rearrange byte order
;	
	; jsr     ldeax0sp
	; sta		_seed+2
	; stx		_seed+0
	; lda		sreg+0
	; sta		_seed+3
	; lda		sreg+1
	; sta		_seed+1


	jsr     ldeax0sp
	sta		_seed+0
	stx		_seed+1
	lda		sreg+0
	sta		_seed+2
	lda		sreg+1
	sta		_seed+3
;
; return seed;
;
	lda     _seed+3
	sta     sreg+1
	lda     _seed+2
	sta     sreg+0
	ldx     _seed+1
	lda     _seed+0
;
	rts

.endproc

