;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_rand
	.import		_srand
	.import		_get_system_time
	.import		_mode
	.import		_clg
	.import		_gcol
	.import		_plot
	.export		_test2
	.export		_main

; ---------------------------------------------------------------
; void __near__ test2 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test2: near

.segment	"CODE"

;
; gcol( 0, COLOUR_BG_BLUE );
;
	jsr     decsp6
	lda     #$00
	jsr     pusha
	lda     #$84
	jsr     _gcol
;
; clg();
;
	jsr     _clg
;
; for( i = 0; i < 100; i++) {
;
	ldy     #$04
	lda     #$00
	sta     (c_sp),y
	iny
	sta     (c_sp),y
L0002:	ldy     #$05
	lda     (c_sp),y
	tax
	dey
	lda     (c_sp),y
	cmp     #$64
	txa
	sbc     #$00
	bvc     L0006
	eor     #$80
L0006:	bpl     L0003
;
; xpos = rand() % 1280;
;
	jsr     _rand
	jsr     pushax
	ldx     #$05
	lda     #$00
	jsr     tosmodax
	ldy     #$02
	jsr     staxysp
;
; ypos = rand() % 1024;
;
	jsr     _rand
	jsr     pushax
	ldx     #$04
	lda     #$00
	jsr     tosmodax
	jsr     stax0sp
;
; gcol( 3, rand() % 8 );
;
	lda     #$03
	jsr     pusha
	jsr     _rand
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     tosmoda0
	jsr     _gcol
;
; plot( 85 , xpos, ypos );
;
	jsr     decsp3
	lda     #$55
	ldy     #$02
	sta     (c_sp),y
	ldy     #$06
	lda     (c_sp),y
	tax
	dey
	lda     (c_sp),y
	ldy     #$00
	sta     (c_sp),y
	iny
	txa
	sta     (c_sp),y
	ldy     #$04
	lda     (c_sp),y
	tax
	dey
	lda     (c_sp),y
	jsr     _plot
;
; for( i = 0; i < 100; i++) {
;
	ldy     #$04
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0002
;
; }
;
L0003:	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; mode(2);
;
	lda     #$02
	jsr     _mode
;
; srand( get_system_time() );
;
	jsr     _get_system_time
	jsr     _srand
;
; test2(); 
;
	jmp     _test2

.endproc

