;
; File generated by cc65 v 2.16 - Git N/A
;
	.fopt		compiler,"cc65 v 2.16 - Git N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__

	.export		_osbyte

	.include        "bbc/os.inc"

.segment	"BSS"


; ---------------------------------------------------------------
; unsigned char __near__ osbyte (unsigned char A_reg, unsigned char X_reg, unsigned char Y_reg)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_osbyte: near

.segment	"CODE"

	jsr     pusha       ; Push Y_reg

	ldy     #$02        ;
	lda     (c_sp),y    ; Pull A_reg off of the C stack
	pha                 ; Push A_reg to CPU stack
  
	dey
	lda     (c_sp),y    ; Pull X_reg off of the C stack
	tax                 ; Set X_reg
  
	dey
	lda     (c_sp),y    ; Pull Y_reg off of the C stack
	tay                 ; Set Y_reg
  
	pla                 ; Pull A reg off CPU stack

	jsr     OSBYTE      ; Returned value in X(low) Y(High)

	tya					; Move XY to AX and return
	ldx		#$00
  
	jmp     incsp3

.endproc
