;
; File generated by cc65 v 2.16 - Git N/A
;
	.fopt		compiler,"cc65 v 2.16 - Git N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__

	.import		_OSWRCH

	.export		_clg
	.export		_cls
	.export		_colour
	.export		_gcol
	.export		_plot

	.include        "bbc/os.inc"


.segment	"BSS"

; ---------------------------------------------------------------
; void __near__ clg ()
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clg: near

.segment	"CODE"

;
; void clg()
;
	lda     #$10
	jsr     _OSWRCH			; Clear graphics area (dec 16)	
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ cls()
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cls: near

.segment	"CODE"

;
; void cls()
;
	lda     #$0c
	jsr     _OSWRCH			; Clear text area (dec 12)
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ colour (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_colour: near

.segment	"CODE"

;
; void colour(byte _colour )
;
	pha						; Push 'colour' to the CPU stack

	lda     #$11
	jsr     _OSWRCH			; Define text colour (dec 17)

	pla
	jsr     _OSWRCH			; Set graphics colour
	
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ gcol (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_gcol: near

.segment	"CODE"

;
; void gcol(byte _k, byte _colour )
;
	pha						; Push 'colour' to the CPU stack

	lda     #$12
	jsr     _OSWRCH			; Define graphics colour (dec 18)

	ldy     #$00
	lda     (sp),y
	jsr     _OSWRCH			; Get _k

	pla
	jsr     _OSWRCH			; Set graphics colour
	
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ plot (unsigned char, int, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_plot: near

.segment	"CODE"

;
; void plot(byte _k, int _x, int _y) {
;
	jsr     pushax
;
; oswrch(25);
;
	lda     #$19
	jsr     _OSWRCH			; Define graphics plot (dec 25)

	ldy     #$04
	lda     (sp),y
	jsr     _OSWRCH

	ldy     #$02
	lda     (sp),y
	jsr     _OSWRCH			; BYTELOW(_x)

	lda     #$02
	jsr     leaa0sp
	jsr     incax1
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _OSWRCH			; BYTEHIGH(_x)

	ldy     #$00
	lda     (sp),y
	jsr     _OSWRCH			; BYTELOW(_y)

	lda     sp
	ldx     sp+1
	jsr     incax1
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _OSWRCH			; BYTEHIGH(_y)

	jmp     incsp5

.endproc

