; ;
; ; File generated by cc65 v 2.16 - Git N/A
; ;
; 	.fopt		compiler,"cc65 v 2.16 - Git N/A"
; 	.setcpu		"6502"
; 	.smart		on
; 	.autoimport	on
; 	.case		on
; 	.debuginfo	off
; 	.importzp	sp, sreg, regsave, regbank
; 	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
; 	.macpack	longbranch
; 	.forceimport	__STARTUP__

	.import		OSWRCH, OSBYTE

	.export		_mode

	.include	"bbc/bbcbasic.inc"
	.include	"bbc/os.inc"

.segment	"BSS"

.segment	"RODATA"
	
; ---------------------------------------------------------------
; void __near__ mode (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_mode: near

;
; void mode(byte _mode)
;
	pha					; Save Mode value on CPU stack

	lda     #$16		; VDU Cmd 22 - change screen mode
	jsr     OSWRCH

	pla					; Restore Mode value to set mode value
	jsr     OSWRCH


	lda		#$84		; Read bottom of display RAM address (HIMEM)
	jsr		OSBYTE
	stx		_himem		; Update BASIC HIMEM
	stx		_basicsp	; Update BASIC Stack Pointer
	sty		_himem+1
	sty		_basicsp+1

	rts

.endproc

