;
; File generated by cc65 v 2.16 - Git N/A
;
	.fopt		compiler,"cc65 v 2.16 - Git N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__

	.export		_osword

	.include        "bbc/os.inc"

.segment	"BSS"

.segment	"RODATA"
L0023:
	.byte	$41,$3A,$25,$64,$2C,$20,$70,$3A,$30,$78,$25,$30,$32,$58,$0D,$0A
	.byte	$00

; ---------------------------------------------------------------
; int __near__ _OSWORD ( byte A_reg, __near__ union osword_parameter_block *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_osword: near

.segment	"CODE"

;
; int _OSWORD( byte A, osword_timer_block* param_block ) {
;
;	AX contain param block pointer (A: Low Byte;  X: High Byte)

	sta		tmp1		; Save AX - pointer to param_block
	stx 	tmp2

	ldy		#$00		;
	lda		(c_sp),y	; Pull A reg from Parameter Stack
	pha					; Push A value to CPU stack

	ldx		tmp1		; Restore XY
	ldy		tmp2
	
	pla					; Restore A
	
	jsr		OSWORD
	jmp		incsp1

.endproc
