;
; File generated by cc65 v 2.16 - Git N/A
;
	.fopt		compiler,"cc65 v 2.16 - Git N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__

	.export		_oswrch

.segment	"BSS"

.segment	"RODATA"
	
; ---------------------------------------------------------------
; void __near__ oswrch (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_oswrch: near

.segment	"CODE"

;
; void oswrch(byte _mode) {
;
	jsr     _oswrch
	rts

.endproc

