;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_service_rom_fs_get_byte
	.import		_service_routine_pre_call
	.import		_service_routine_post_call
	.import		_swr_print_str
	.import		_swr_print_newline
	.import		_dbg_print_rom

.segment	"RODATA"

S000A:
	.byte	$73,$65,$72,$76,$69,$63,$65,$5F,$72,$6F,$6D,$5F,$66,$73,$5F,$67
	.byte	$65,$74,$5F,$62,$79,$74,$65,$3A,$42,$65,$67,$69,$6E,$00
S000B:
	.byte	$73,$65,$72,$76,$69,$63,$65,$5F,$72,$6F,$6D,$5F,$66,$73,$5F,$67
	.byte	$65,$74,$5F,$62,$79,$74,$65,$3A,$45,$6E,$64,$00

; ---------------------------------------------------------------
; void __near__ service_rom_fs_get_byte (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_rom_fs_get_byte: near

.segment	"CODE"

;
; swr_print_str( "service_rom_fs_get_byte:Begin" );
;
	lda     #<(S000A)
	ldx     #>(S000A)
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jsr     _swr_print_newline
;
; dbg_print_rom();
;
	jsr     _dbg_print_rom
;
; service_routine_pre_call();   
;
	jsr     _service_routine_pre_call
;
; service_routine_post_call();
;
	jsr     _service_routine_post_call
;
; swr_print_str( "service_rom_fs_get_byte:End" );
;
	lda     #<(S000B)
	ldx     #>(S000B)
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jmp     _swr_print_newline

.endproc

