;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_service_auto_boot
	.import		_service_routine_pre_call
	.import		_service_routine_post_call
	.import		_print_rom_title
	.import		_swr_print_newline

; ---------------------------------------------------------------
; void __near__ service_auto_boot (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_auto_boot: near

.segment	"CODE"

;
; service_routine_pre_call();   
;
	jsr     _service_routine_pre_call
;
; print_rom_title();
;
	jsr     _print_rom_title
;
; swr_print_newline();
;
	jsr     _swr_print_newline
;
; service_routine_post_call();
;
	jmp     _service_routine_post_call

.endproc

