;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.importzp	_aws
	.importzp	_Yreg
	.export		_service_claim_absolute_ws

; ---------------------------------------------------------------
; void __near__ service_claim_absolute_ws (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_claim_absolute_ws: near

.segment	"CODE"

;
; ws = 0x0e + ( sizeof(struct aws) / 256 );   // Start with OSHWM + size of AWS in 256 byte pages + 1
;
	jsr     decsp1
	lda     #$0E
	ldy     #$00
	sta     (c_sp),y
;
; if ( ws > Yreg ) {
;
	cmp     _Yreg
	bcc     L0002
	beq     L0002
;
; aws = (struct aws *)0x0e00;
;
	tax
	sty     _aws
	stx     _aws+1
;
; Yreg = ws;
;
	lda     (c_sp),y
	sta     _Yreg
;
; }
;
L0002:	jmp     incsp1

.endproc

