;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.importzp	_Areg
	.importzp	_Yreg
	.importzp	_cmd_ptr
	.import		_claim_absolute_static_workspace
	.import		_strcmp_cr
	.import		_commands
	.import		_swr_callback
	.export		_service_unknown_command

; ---------------------------------------------------------------
; void __near__ service_unknown_command (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_unknown_command: near

.segment	"CODE"

;
; int idx = 0;
;
	jsr     push0
;
; claim_absolute_static_workspace();       // I need the AWS so claim it.
;
	jsr     decsp2
	jsr     _claim_absolute_static_workspace
;
; cmd_str = &cmd_ptr[Yreg];                   // cmd pointers to the start of the command string
;
	lda     _cmd_ptr
	ldx     _cmd_ptr+1
	clc
	adc     _Yreg
	bcc     L0009
	inx
L0009:	jsr     stax0sp
;
; for( idx = 0; idx < cmd_count; idx++ ) {
;
	ldy     #$02
	lda     #$00
	sta     (c_sp),y
	iny
	sta     (c_sp),y
L0002:	ldy     #$03
	lda     (c_sp),y
	tax
	dey
	lda     (c_sp),y
	cmp     #$05
	txa
	sbc     #$00
	bvc     L0006
	eor     #$80
L0006:	bpl     L0003
;
; if (  strcmp_cr( cmd_str, commands[idx].command ) == 0  ) {
;
	jsr     pushw0sp
	ldy     #$05
	lda     (c_sp),y
	tax
	dey
	lda     (c_sp),y
	jsr     mulax6
	clc
	adc     #<(_commands)
	sta     ptr1
	txa
	adc     #>(_commands)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _strcmp_cr
	cpx     #$00
	bne     L0004
	cmp     #$00
	bne     L0004
;
; swr_callback(commands[idx].func); // Call the recognised command
;
	ldy     #$03
	lda     (c_sp),y
	tax
	dey
	lda     (c_sp),y
	jsr     mulax6
	clc
	adc     #<(_commands)
	sta     ptr1
	txa
	adc     #>(_commands)
	sta     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _swr_callback
;
; Areg = 0;                        // Prevent further ROMs from processing this cmd
;
	lda     #$00
	sta     _Areg
;
; break;
;
	jmp     incsp4
;
; for( idx = 0; idx < cmd_count; idx++ ) {
;
L0004:	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0002
;
; }
;
L0003:	jmp     incsp4

.endproc

