;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_dbg_print_rom
	.export		_service_nmi_release

; ---------------------------------------------------------------
; void __near__ service_nmi_release (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_nmi_release: near

.segment	"CODE"

;
; dbg_print_rom();
;
	jmp     _dbg_print_rom

.endproc

