;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.importzp	_pws
	.importzp	_Xreg
	.importzp	_Yreg
	.import		_paged_rom_ws
	.export		_service_claim_private_ws

; ---------------------------------------------------------------
; void __near__ service_claim_private_ws (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_claim_private_ws: near

.segment	"CODE"

;
; pws = (struct pws *)(Yreg + ( PWS_SIZE / 256 ) + 1 );  // Struct pws declared in /include/bbcswr/swr.h
;
	ldx     #$00
	lda     _Yreg
	clc
	adc     #$01
	bcc     L0003
	inx
L0003:	sta     _pws
	stx     _pws+1
;
; paged_rom_ws[Xreg] = (byte)(pws);       // Save PWS pointer into Paged ROM Workspace Storage @ 0x0df0
;
	ldy     _Xreg
	lda     _pws
	sta     _paged_rom_ws,y
;
; Yreg = (byte)pws;           // Return PWS pointer to BBC OS
;
	sta     _Yreg
;
; pws = (struct pws *)((byte)(pws) * 256);     // Define how many pages required for private workspace
;
	ldx     _pws
	lda     #$00
	sta     _pws
	stx     _pws+1
;
; asm("ldy #%b", sizeof(pws->c_stack));      // Offset to PWS->c_stack_ptr
;
	ldy     #$80
;
; asm("lda #%b", sizeof(pws->c_stack)-1);      // Size of C Stack -1 ($7f)
;
	lda     #$7F
;
; asm("sta (_pws),y");           // Save stack point in c_stack_pointer
;
	sta     (_pws),y
;
; }
;
	rts

.endproc

