;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.importzp	_Xreg
	.importzp	_OS_Areg
	.import		_paged_rom_ws
	.export		_service_claim_static_ws
	.export		_service_release_static_ws

; ---------------------------------------------------------------
; void __near__ service_claim_static_ws (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_claim_static_ws: near

.segment	"CODE"

;
; if ( ( paged_rom_ws[Xreg] & 0x80 ) != 0x0 ) { // Is this ROM the AWS Owner
;
	ldy     _Xreg
	lda     _paged_rom_ws,y
	and     #$80
	beq     L0002
;
; OS_Areg = paged_rom_ws[Xreg] | 0x80; // Set Bit 7 = Claim AWS Owner
;
	ldy     _Xreg
	lda     _paged_rom_ws,y
	ora     #$80
	sta     _OS_Areg
;
; paged_rom_ws[Xreg] = OS_Areg;
;
	ldy     _Xreg
	lda     _OS_Areg
	sta     _paged_rom_ws,y
;
; asm("lda #143");
;
	lda     #143
;
; asm("ldx #10");
;
	ldx     #10
;
; asm("ldy #0");
;
	ldy     #0
;
; asm("jsr  $fffe");
;
	jsr     $fffe
;
; paged_rom_ws[Xreg] = OS_Areg;
;
	ldy     _Xreg
	lda     _OS_Areg
	sta     _paged_rom_ws,y
;
; }
;
L0002:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ service_release_static_ws (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_release_static_ws: near

.segment	"CODE"

;
; OS_Areg = paged_rom_ws[Xreg] & 0x7f; // Set Bit 7 = Claim AWS Owner
;
	ldy     _Xreg
	lda     _paged_rom_ws,y
	and     #$7F
	sta     _OS_Areg
;
; paged_rom_ws[Xreg] = OS_Areg;
;
	ldy     _Xreg
	lda     _OS_Areg
	sta     _paged_rom_ws,y
;
; }
;
	rts

.endproc

