;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.importzp	_aws
	.importzp	_Yreg
	.export		_service_claim_absolute_ws

; ---------------------------------------------------------------
; void __near__ service_claim_absolute_ws (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_claim_absolute_ws: near

.segment	"CODE"

;
; aws = (struct aws *)( Yreg + ( AWS_SIZE / 256 ) + 1 );
;
	ldx     #$00
	lda     _Yreg
	clc
	adc     #$01
	bcc     L0003
	inx
L0003:	sta     _aws
	stx     _aws+1
;
; if ( (byte)aws > Yreg ) {
;
	lda     _aws
	cmp     _Yreg
	bcc     L0004
	beq     L0004
;
; Yreg = (byte)aws;
;
	sta     _Yreg
;
; aws = (struct aws *)0x0e00;
;
	ldx     #$0E
	lda     #$00
	sta     _aws
	stx     _aws+1
;
; }
;
L0004:	rts

.endproc

