;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.importzp	_pws
	.importzp	_Xreg
	.importzp	_Yreg
	.import		_paged_rom_ws
	.export		_service_claim_private_ws

; ---------------------------------------------------------------
; void __near__ service_claim_private_ws (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_claim_private_ws: near

.segment	"CODE"

;
; Yreg += ( sizeof(struct pws) / 256 ) + 1;   // Struct pws declared in /include/bbc/swr.h
;
	inc     _Yreg
;
; paged_rom_ws[Xreg] = Yreg;          // Save PWS pointer into Paged ROM Workspace Storage @ 0x0df0
;
	ldy     _Xreg
	lda     _Yreg
	sta     _paged_rom_ws,y
;
; pws = Yreg * 256;                   // Define how many pages required for private workspace
;
	tax
	lda     #$00
	sta     _pws
	stx     _pws+1
;
; }
;
	rts

.endproc

