;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_swr_print_str
	.import		_swr_print_newline
	.import		_intdec
	.importzp	_aws
	.importzp	_Areg
	.importzp	_OS_Areg
	.importzp	_OS_Xreg
	.importzp	_OS_Yreg
	.export		_print_osbyte
	.export		_service_unknown_osbyte

.segment	"RODATA"

S000A:
	.byte	$6F,$73,$62,$79,$74,$65,$20,$00
S000C:
	.byte	$2C,$00
S000B	:=	S000C+0

; ---------------------------------------------------------------
; void __near__ print_osbyte (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_print_osbyte: near

.segment	"CODE"

;
; swr_print_str( "osbyte " );
;
	ldy     #$0C
	jsr     subysp
	lda     #<(S000A)
	ldx     #>(S000A)
	jsr     _swr_print_str
;
; swr_print_str( intdec( OS_Areg, buf ) );
;
	lda     _OS_Areg
	jsr     pusha0
	lda     c_sp
	ldx     c_sp+1
	clc
	adc     #$02
	bcc     L0002
	inx
L0002:	jsr     _intdec
	jsr     _swr_print_str
;
; swr_print_str( "," );
;
	lda     #<(S000B)
	ldx     #>(S000B)
	jsr     _swr_print_str
;
; swr_print_str( intdec( OS_Xreg, buf ) );
;
	lda     _OS_Xreg
	jsr     pusha0
	lda     c_sp
	ldx     c_sp+1
	clc
	adc     #$02
	bcc     L0003
	inx
L0003:	jsr     _intdec
	jsr     _swr_print_str
;
; swr_print_str( "," );
;
	lda     #<(S000C)
	ldx     #>(S000C)
	jsr     _swr_print_str
;
; swr_print_str( intdec( OS_Yreg, buf ) );
;
	lda     _OS_Yreg
	jsr     pusha0
	lda     c_sp
	ldx     c_sp+1
	clc
	adc     #$02
	bcc     L0004
	inx
L0004:	jsr     _intdec
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jsr     _swr_print_newline
;
; }
;
	ldy     #$0C
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ service_unknown_osbyte (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_unknown_osbyte: near

.segment	"CODE"

;
; switch ( OS_Areg ) {
;
	lda     _OS_Areg
;
; }
;
	cmp     #$1A
	beq     L0004
	cmp     #$1B
	beq     L0005
	cmp     #$1C
	beq     L0006
	rts
;
; print_osbyte();
;
L0004:	jsr     _print_osbyte
;
; aws->tmp1 = 10;
;
	lda     #$0A
;
; break;
;
	jmp     L000A
;
; print_osbyte();
;
L0005:	jsr     _print_osbyte
;
; aws->tmp1 = 20;
;
	lda     #$14
;
; break;
;
	jmp     L000A
;
; print_osbyte();
;
L0006:	jsr     _print_osbyte
;
; aws->tmp1 = 30;
;
	lda     #$1E
L000A:	ldy     #$80
	sta     (_aws),y
;
; Areg = 0;                       // Prevent further ROMs from processing this cmd
;
	lda     #$00
	sta     _Areg
;
; }
;
	rts

.endproc

