;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_service_claim_pws_hazel
	.import		_service_routine_pre_call
	.import		_service_routine_post_call

; ---------------------------------------------------------------
; void __near__ service_claim_pws_hazel (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_claim_pws_hazel: near

.segment	"CODE"

;
; service_routine_pre_call();   
;
	jsr     _service_routine_pre_call
;
; service_routine_post_call();
;
	jmp     _service_routine_post_call

.endproc

