;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.importzp	_cmd_ptr
	.import		_strcmp_cr
	.import		_commands
	.import		_swr_callback
	.export		_service_unknown_command

; ---------------------------------------------------------------
; long __near__ service_unknown_command (unsigned char A, unsigned char X, unsigned char Y)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_unknown_command: near

.segment	"CODE"

;
; long service_unknown_command( byte A, byte X, byte Y ) {
;
	jsr     pusha
;
; int cmd_idx = 0;
;
	jsr     push0
;
; cmd_str = &cmd_ptr[Y];       // cmd pointers to the start of the command string
;
	jsr     decsp2
	ldy     #$04
	lda     (c_sp),y
	clc
	adc     _cmd_ptr
	ldx     _cmd_ptr+1
	bcc     L0009
	inx
L0009:	jsr     stax0sp
;
; for( cmd_idx = 0; cmd_idx < cmd_count; cmd_idx++ ) {
;
	ldy     #$02
	lda     #$00
	sta     (c_sp),y
	iny
	sta     (c_sp),y
L0002:	ldy     #$03
	lda     (c_sp),y
	tax
	dey
	lda     (c_sp),y
	cmp     #$05
	txa
	sbc     #$00
	bvc     L0006
	eor     #$80
L0006:	bpl     L0003
;
; if (  strcmp_cr( cmd_str, commands[cmd_idx].command ) == 0  ) {
;
	jsr     pushw0sp
	ldy     #$07
	jsr     pushwysp
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_commands)
	tay
	txa
	adc     #>(_commands)
	tax
	tya
	jsr     _strcmp_cr
	cpx     #$00
	bne     L0004
	cmp     #$00
	bne     L0004
;
; swr_callback( commands[cmd_idx].func ); // Call the recognised command
;
	ldy     #$05
	jsr     pushwysp
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_commands)
	sta     ptr1
	txa
	adc     #>(_commands)
	sta     ptr1+1
	ldy     #$13
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _swr_callback
;
; A = 0;                          // Prevent further ROMs from processing this cmd
;
	lda     #$00
	ldy     #$06
	sta     (c_sp),y
;
; break;
;
	jmp     L0003
;
; for( cmd_idx = 0; cmd_idx < cmd_count; cmd_idx++ ) {
;
L0004:	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0002
;
; return  (long)( (long)Y << 16 )  + ( (int)X << 8 ) + A; // Return the values of A, X, Y
;
L0003:	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	stx     sreg+1
	sta     sreg
	txa
	jsr     pusheax
	ldy     #$09
	lda     (c_sp),y
	tax
	lda     #$00
	jsr     axlong
	jsr     tosaddeax
	jsr     pusheax
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	jsr     tosadd0ax
;
; }
;
	jmp     incsp7

.endproc

