;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_dbg_print_rom
	.export		_service_unknown_status

; ---------------------------------------------------------------
; long __near__ service_unknown_status (unsigned char A, unsigned char X, unsigned char Y)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_unknown_status: near

.segment	"CODE"

;
; long service_unknown_status( byte A, byte X, byte Y ) {                  // Do nothing, but allows you to do something
;
	jsr     pusha
;
; dbg_print_rom();
;
	jsr     _dbg_print_rom
;
; return  (long)( (long)Y << 16 )  + ( (int)X << 8 ) + A;
;
	ldx     #$00
	lda     (c_sp,x)
	stx     sreg+1
	sta     sreg
	txa
	jsr     pusheax
	ldy     #$05
	lda     (c_sp),y
	tax
	lda     #$00
	jsr     axlong
	jsr     tosaddeax
	jsr     pusheax
	ldy     #$06
	ldx     #$00
	lda     (c_sp),y
	jsr     tosadd0ax
;
; }
;
	jmp     incsp3

.endproc

