;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_service_interactive_help

; ---------------------------------------------------------------
; void __near__ service_interactive_help (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_interactive_help: near

.segment	"CODE"

;
; }
;
	rts

.endproc

