;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_swr_print_str
	.import		_swr_print_newline
	.import		_swr_print_space
	.importzp	_Areg
	.importzp	_Yreg
	.importzp	_cmd_ptr
	.import		_SWR_Title
	.import		_print_rom_title
	.import		_claim_absolute_static_workspace
	.import		_strcmp_cr
	.import		_commands
	.export		_service_help

; ---------------------------------------------------------------
; void __near__ service_help (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_help: near

.segment	"CODE"

;
; int cmd_idx = 0;
;
	jsr     decsp2
	jsr     push0
;
; claim_absolute_static_workspace();      // I need the AWS so claim it.
;
	jsr     _claim_absolute_static_workspace
;
; help_cmd = &cmd_ptr[Yreg];                   // cmd pointers to the start of the command string
;
	lda     _cmd_ptr
	ldx     _cmd_ptr+1
	clc
	adc     _Yreg
	bcc     L000B
	inx
L000B:	ldy     #$02
	jsr     staxysp
;
; if ( help_cmd[0] == 0x0d ) {                 // No command supplied
;
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	cmp     #$0D
	bne     L0002
;
; print_rom_title();
;
	jsr     _print_rom_title
;
; else {
;
	jmp     incsp4
;
; if ( strcmp_cr( help_cmd, SWR_Title ) == 0 ) {
;
L0002:	ldy     #$05
	jsr     pushwysp
	lda     #<(_SWR_Title)
	ldx     #>(_SWR_Title)
	jsr     _strcmp_cr
	cpx     #$00
	jne     L0004
	cmp     #$00
	bne     L0004
;
; print_rom_title();
;
	jsr     _print_rom_title
;
; for( cmd_idx = 0; cmd_idx < cmd_count; cmd_idx++ ) {
;
	ldy     #$00
	tya
	sta     (c_sp),y
	iny
	sta     (c_sp),y
L0006:	ldy     #$01
	lda     (c_sp),y
	tax
	dey
	lda     (c_sp),y
	cmp     #$05
	txa
	sbc     #$00
	bvc     L000A
	eor     #$80
L000A:	asl     a
	tya
	bcc     L000D
;
; swr_print_space(1);
;
	tax
	lda     #$01
	jsr     _swr_print_space
;
; swr_print_str( commands[cmd_idx].command );
;
	ldy     #$01
	lda     (c_sp),y
	tax
	dey
	lda     (c_sp),y
	jsr     mulax6
	clc
	adc     #<(_commands)
	sta     ptr1
	txa
	adc     #>(_commands)
	sta     ptr1+1
	iny
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _swr_print_str
;
; swr_print_space(1);
;
	ldx     #$00
	lda     #$01
	jsr     _swr_print_space
;
; swr_print_str( commands[cmd_idx].description );
;
	ldy     #$01
	lda     (c_sp),y
	tax
	dey
	lda     (c_sp),y
	jsr     mulax6
	clc
	adc     #<(_commands)
	sta     ptr1
	txa
	adc     #>(_commands)
	sta     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jsr     _swr_print_newline
;
; for( cmd_idx = 0; cmd_idx < cmd_count; cmd_idx++ ) {
;
	ldx     #$00
	lda     #$01
	jsr     addeq0sp
	jmp     L0006
;
; Areg = 0;                       // Prevent further ROMs from processing this cmd
;
L000D:	sta     _Areg
;
; }
;
L0004:	jmp     incsp4

.endproc

