;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.importzp	_Areg
	.importzp	_Yreg
	.importzp	_cmd_ptr
	.export		_service_unknown_command
	.import		_service_routine_pre_call
	.import		_service_routine_post_call
	.import		_strcmp_cr
	.import		_swr_print_str
	.import		_swr_print_newline
	.import		_commands
	.import		_swr_callback
	.import		_dbg_print_rom

.segment	"RODATA"

S000A:
	.byte	$73,$65,$72,$76,$69,$63,$65,$5F,$75,$6E,$6B,$6E,$6F,$77,$6E,$5F
	.byte	$63,$6F,$6D,$6D,$61,$6E,$64,$3A,$42,$65,$67,$69,$6E,$00
S000B:
	.byte	$73,$65,$72,$76,$69,$63,$65,$5F,$75,$6E,$6B,$6E,$6F,$77,$6E,$5F
	.byte	$63,$6F,$6D,$6D,$61,$6E,$64,$3A,$45,$6E,$64,$00

; ---------------------------------------------------------------
; void __near__ service_unknown_command (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_unknown_command: near

.segment	"CODE"

;
; int cmd_idx = 0;
;
	jsr     push0
;
; swr_print_str( "service_unknown_command:Begin" );
;
	jsr     decsp2
	lda     #<(S000A)
	ldx     #>(S000A)
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jsr     _swr_print_newline
;
; dbg_print_rom();
;
	jsr     _dbg_print_rom
;
; service_routine_pre_call();   
;
	jsr     _service_routine_pre_call
;
; cmd_str = &cmd_ptr[Yreg];      // cmd pointers to the start of the command string
;
	lda     _cmd_ptr
	ldx     _cmd_ptr+1
	clc
	adc     _Yreg
	bcc     L0009
	inx
L0009:	jsr     stax0sp
;
; for( cmd_idx = 0; cmd_idx < cmd_count; cmd_idx++ ) {
;
	ldy     #$02
	lda     #$00
	sta     (c_sp),y
	iny
	sta     (c_sp),y
L0002:	ldy     #$03
	lda     (c_sp),y
	tax
	dey
	lda     (c_sp),y
	cmp     #$05
	txa
	sbc     #$00
	bvc     L0006
	eor     #$80
L0006:	asl     a
	lda     #$00
	tax
	rol     a
	beq     L0003
;
; if (  strcmp_cr( cmd_str, commands[cmd_idx].command ) == 0  ) {
;
	jsr     pushw0sp
	ldy     #$07
	jsr     pushwysp
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_commands)
	tay
	txa
	adc     #>(_commands)
	tax
	tya
	jsr     _strcmp_cr
	cpx     #$00
	bne     L0004
	cmp     #$00
	bne     L0004
;
; swr_callback( commands[cmd_idx].func ); // Call the recognised command
;
	ldy     #$05
	jsr     pushwysp
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_commands)
	sta     ptr1
	txa
	adc     #>(_commands)
	sta     ptr1+1
	ldy     #$13
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _swr_callback
;
; Areg = 0;                         // Prevent further ROMs from processing this cmd
;
	ldx     #$00
	txa
	sta     _Areg
;
; break;
;
	jmp     L0003
;
; for( cmd_idx = 0; cmd_idx < cmd_count; cmd_idx++ ) {
;
L0004:	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0002
;
; service_routine_post_call();
;
L0003:	jsr     _service_routine_post_call
;
; swr_print_str( "service_unknown_command:End" );
;
	lda     #<(S000B)
	ldx     #>(S000B)
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jsr     _swr_print_newline
;
; dbg_print_rom();
;
	jsr     _dbg_print_rom
;
; }
;
	jmp     incsp4

.endproc

