;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_swr_print_str
	.import		_swr_print_newline
	.import		_swr_print_space
	.importzp	_cmd_ptr
	.import		_SWR_Title
	.import		_print_rom_title
	.import		_strcmp_cr
	.import		_dbg_print_rom
	.import		_commands
	.export		_eax
	.export		_service_help
	.export		_test

.segment	"BSS"

_eax:
	.res	4,$00

; ---------------------------------------------------------------
; struct _eax __near__ service_help (unsigned char A, unsigned char X, unsigned char Y)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_help: near

.segment	"CODE"

;
; struct _eax service_help( byte A, byte X, byte Y ) {
;
	jsr     pusha
;
; dbg_print_rom();
;
	jsr     decsp3
	jsr     _dbg_print_rom
;
; help_cmd = &cmd_ptr[Y];       // cmd pointers to the start of the command string
;
	ldy     #$03
	lda     (c_sp),y
	clc
	adc     _cmd_ptr
	ldx     _cmd_ptr+1
	bcc     L000B
	inx
L000B:	jsr     stax0sp
;
; if ( help_cmd[0] == 0x0d ) {     // No command supplied
;
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	cmp     #$0D
	bne     L0002
;
; swr_print_newline();
;
	jsr     _swr_print_newline
;
; print_rom_title();
;
	jsr     _print_rom_title
;
; else {
;
	jmp     L0004
;
; if ( strcmp_cr( help_cmd, SWR_Title ) == 0 ) {
;
L0002:	jsr     pushw0sp
	lda     #<(_SWR_Title)
	ldx     #>(_SWR_Title)
	jsr     _strcmp_cr
	cpx     #$00
	bne     L0004
	cmp     #$00
	bne     L0004
;
; swr_print_newline();
;
	jsr     _swr_print_newline
;
; print_rom_title();
;
	jsr     _print_rom_title
;
; for( cmd_idx = 0; cmd_idx < cmd_count; cmd_idx++ ) {
;
	lda     #$00
	ldy     #$02
L000C:	sta     (c_sp),y
	ldx     #$00
	lda     (c_sp),y
	cmp     #$05
	bcs     L000D
;
; swr_print_space(1);
;
	lda     #$01
	jsr     _swr_print_space
;
; swr_print_str( commands[cmd_idx].command );
;
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha0
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_commands)
	tay
	txa
	adc     #>(_commands)
	tax
	tya
	jsr     _swr_print_str
;
; swr_print_space(1);
;
	ldx     #$00
	lda     #$01
	jsr     _swr_print_space
;
; swr_print_str( commands[cmd_idx].description );
;
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha0
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_commands)
	tay
	txa
	adc     #>(_commands)
	tax
	tya
	clc
	adc     #$06
	bcc     L000A
	inx
L000A:	jsr     _swr_print_str
;
; swr_print_newline();
;
	jsr     _swr_print_newline
;
; for( cmd_idx = 0; cmd_idx < cmd_count; cmd_idx++ ) {
;
	ldy     #$02
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L000C
;
; A = 0;         // Prevent further ROMs from processing this cmd
;
L000D:	txa
	ldy     #$05
	sta     (c_sp),y
;
; dbg_print_rom();
;
L0004:	jsr     _dbg_print_rom
;
; eax.a = A;
;
	ldy     #$05
	lda     (c_sp),y
	sta     _eax
;
; eax.x = X;
;
	dey
	lda     (c_sp),y
	sta     _eax+1
;
; eax.y = Y;
;
	dey
	lda     (c_sp),y
	sta     _eax+2
;
; return eax;
;
	lda     _eax+3
	sta     sreg+1
	lda     _eax+2
	sta     sreg
	ldx     _eax+1
	lda     _eax
;
; }
;
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ test (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test: near

.segment	"CODE"

;
; t = service_help(1,2,3);
;
	jsr     decsp6
	lda     #$01
	tay
	sta     (c_sp),y
	lda     #$02
	dey
	sta     (c_sp),y
	lda     #$03
	jsr     _service_help
	jsr     steax0sp
;
; }
;
	jmp     incsp4

.endproc

