;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.importzp	_Xreg
	.import		_paged_rom_ws
	.export		_claim_static_aws
	.export		_service_release_static_ws

; ---------------------------------------------------------------
; void __near__ claim_static_aws (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_claim_static_aws: near

.segment	"CODE"

;
; if ( ( paged_rom_ws[Xreg] & 0x80 ) == 0x0 ) { // Is this ROM the AWS Owner?
;
	ldy     _Xreg
	lda     _paged_rom_ws,y
	and     #$80
	bne     L0002
;
; asm("ldx #$0a");         // Service call - Claim Static AWS
;
	ldx     #$0a
;
; asm("jsr  _issue_rom_service_call");
;
	jsr     _issue_rom_service_call
;
; paged_rom_ws[Xreg] = paged_rom_ws[Xreg] | 0x80;  // Set Bit 7 = Claim AWS Ownership
;
	lda     #<(_paged_rom_ws)
	ldx     #>(_paged_rom_ws)
	clc
	adc     _Xreg
	bcc     L0005
	inx
L0005:	sta     ptr1
	stx     ptr1+1
	ldy     _Xreg
	lda     _paged_rom_ws,y
	ora     #$80
	ldy     #$00
	sta     (ptr1),y
;
; }
;
L0002:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ service_release_static_ws (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_release_static_ws: near

.segment	"CODE"

;
; paged_rom_ws[Xreg] = paged_rom_ws[Xreg] & 0x7f;   // Clear Bit 7 = Release AWS Ownership
;
	lda     #<(_paged_rom_ws)
	ldx     #>(_paged_rom_ws)
	clc
	adc     _Xreg
	bcc     L0002
	inx
L0002:	sta     ptr1
	stx     ptr1+1
	ldy     _Xreg
	lda     _paged_rom_ws,y
	and     #$7F
	ldy     #$00
	sta     (ptr1),y
;
; }
;
	rts

.endproc

