;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_swr_print_newline
	.import		_print_rom_title
	.export		_service_auto_boot

; ---------------------------------------------------------------
; void __near__ service_auto_boot (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_service_auto_boot: near

.segment	"CODE"

;
; print_rom_title();
;
	jsr     _print_rom_title
;
; swr_print_newline();
;
	jmp     _swr_print_newline

.endproc

