;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_swr_print_str
	.import		_swr_print_newline
	.import		_swr_print_space
	.import		_SWR_Title
	.import		_SWR_Version
	.export		_print_rom_title

; ---------------------------------------------------------------
; void __near__ print_rom_title (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_print_rom_title: near

.segment	"CODE"

;
; swr_print_str( (char*) SWR_Title );
;
	lda     #<(_SWR_Title)
	ldx     #>(_SWR_Title)
	jsr     _swr_print_str
;
; swr_print_space(1);
;
	ldx     #$00
	lda     #$01
	jsr     _swr_print_space
;
; swr_print_str( (char*) SWR_Version );
;
	lda     #<(_SWR_Version)
	ldx     #>(_SWR_Version)
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jsr     _swr_print_newline
;
; swr_print_newline();
;
	jmp     _swr_print_newline

.endproc

