;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_swr_print_str
	.import		_swr_print_newline
	.export		_commands
	.export		_cmd1
	.export		_desc1
	.export		_func1
	.export		_cmd2
	.export		_desc2
	.export		_func2
	.export		_cmd3
	.export		_desc3
	.export		_func3
	.export		_cmd4
	.export		_desc4
	.export		_func4
	.export		_cmd5
	.export		_desc5
	.export		_func5

.segment	"RODATA"

_cmd1:
	.byte	$46,$31,$00
_desc1:
	.byte	$61,$62,$63,$00
_cmd2:
	.byte	$46,$32,$00
_desc2:
	.byte	$64,$65,$66,$00
_cmd3:
	.byte	$46,$33,$00
_desc3:
	.byte	$67,$68,$69,$00
_cmd4:
	.byte	$46,$34,$00
_desc4:
	.byte	$67,$68,$69,$00
_cmd5:
	.byte	$46,$35,$00
_desc5:
	.byte	$67,$68,$69,$00
_commands:
	.addr	_cmd1
	.addr	_desc1
	.addr	_func1
	.addr	_cmd2
	.addr	_desc2
	.addr	_func2
	.addr	_cmd3
	.addr	_desc3
	.addr	_func3
	.addr	_cmd4
	.addr	_desc4
	.addr	_func4
	.addr	_cmd5
	.addr	_desc5
	.addr	_func5
S0015:
	.byte	$66,$75,$6E,$63,$34,$00
S0012:
	.byte	$66,$75,$6E,$63,$33,$00
S000F:
	.byte	$66,$75,$6E,$63,$32,$00
S000C:
	.byte	$66,$75,$6E,$63,$31,$00
S0018:
	.byte	$66,$75,$6E,$63,$35,$00

; ---------------------------------------------------------------
; void __near__ func1 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_func1: near

.segment	"CODE"

;
; swr_print_str("func1");
;
	lda     #<(S000C)
	ldx     #>(S000C)
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jmp     _swr_print_newline

.endproc

; ---------------------------------------------------------------
; void __near__ func2 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_func2: near

.segment	"CODE"

;
; swr_print_str("func2");
;
	lda     #<(S000F)
	ldx     #>(S000F)
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jmp     _swr_print_newline

.endproc

; ---------------------------------------------------------------
; void __near__ func3 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_func3: near

.segment	"CODE"

;
; swr_print_str("func3");
;
	lda     #<(S0012)
	ldx     #>(S0012)
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jmp     _swr_print_newline

.endproc

; ---------------------------------------------------------------
; void __near__ func4 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_func4: near

.segment	"CODE"

;
; swr_print_str("func4");
;
	lda     #<(S0015)
	ldx     #>(S0015)
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jmp     _swr_print_newline

.endproc

; ---------------------------------------------------------------
; void __near__ func5 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_func5: near

.segment	"CODE"

;
; swr_print_str("func5");
;
	lda     #<(S0018)
	ldx     #>(S0018)
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jmp     _swr_print_newline

.endproc

