;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_swr_print_str
	.import		_swr_print_newline
	.export		_commands
	.export		_func1
	.export		_func2
	.export		_func3
	.export		_func4
	.export		_func5

.segment	"RODATA"

_commands:
	.byte	$46,$31,$00
	.res	3,$00
	.byte	$61,$62,$63,$00
	.res	8,$00
	.addr	_func1
	.byte	$46,$32,$00
	.res	3,$00
	.byte	$64,$65,$66,$00
	.res	8,$00
	.addr	_func2
	.byte	$46,$33,$00
	.res	3,$00
	.byte	$67,$68,$69,$00
	.res	8,$00
	.addr	_func3
	.byte	$46,$34,$00
	.res	3,$00
	.byte	$6A,$6B,$6C,$00
	.res	8,$00
	.addr	_func4
	.byte	$46,$35,$00
	.res	3,$00
	.byte	$6D,$6E,$6F,$00
	.res	8,$00
	.addr	_func5
S000D:
	.byte	$43,$6D,$64,$3A,$20,$46,$75,$6E,$63,$20,$34,$00
S000C:
	.byte	$43,$6D,$64,$3A,$20,$46,$75,$6E,$63,$20,$33,$00
S000B:
	.byte	$43,$6D,$64,$3A,$20,$46,$75,$6E,$63,$20,$32,$00
S000A:
	.byte	$43,$6D,$64,$3A,$20,$46,$75,$6E,$63,$20,$31,$00
S000E:
	.byte	$43,$6D,$64,$3A,$20,$46,$75,$6E,$63,$20,$35,$00

; ---------------------------------------------------------------
; void __near__ func1 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_func1: near

.segment	"CODE"

;
; swr_print_str("Cmd: Func 1");
;
	lda     #<(S000A)
	ldx     #>(S000A)
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jmp     _swr_print_newline

.endproc

; ---------------------------------------------------------------
; void __near__ func2 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_func2: near

.segment	"CODE"

;
; swr_print_str("Cmd: Func 2");
;
	lda     #<(S000B)
	ldx     #>(S000B)
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jmp     _swr_print_newline

.endproc

; ---------------------------------------------------------------
; void __near__ func3 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_func3: near

.segment	"CODE"

;
; swr_print_str("Cmd: Func 3");
;
	lda     #<(S000C)
	ldx     #>(S000C)
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jmp     _swr_print_newline

.endproc

; ---------------------------------------------------------------
; void __near__ func4 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_func4: near

.segment	"CODE"

;
; swr_print_str("Cmd: Func 4");
;
	lda     #<(S000D)
	ldx     #>(S000D)
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jmp     _swr_print_newline

.endproc

; ---------------------------------------------------------------
; void __near__ func5 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_func5: near

.segment	"CODE"

;
; swr_print_str("Cmd: Func 5");
;
	lda     #<(S000E)
	ldx     #>(S000E)
	jsr     _swr_print_str
;
; swr_print_newline();
;
	jmp     _swr_print_newline

.endproc

